src/constants/contexts.ts, src/constants/permissionLevels.ts
This changes will prevent JS projects to use enums.
close #8
=> refactor: remove const from enums

package.json, yarn.lock
This creates conflicts when resolving decorations (declarations.ts) with the type resolution
=> fix: remove caret version on fastify

src/config.ts, src/utils/cookie.ts, src/utils/navigation.test.ts, src/utils/navigation.ts
This PR fixes the missing protocol in the builder method for the link to items in notification emails.
closes #51
=> 51 fix notification link protocol

src/config.ts, src/utils/navigation.test.ts, src/utils/navigation.ts, test/fixtures.ts
This PR deprecates the use of the `host` and `protocol` parameters in `buildItemLinkForBuilder`.
It introduces a new function signature with `origin` parameter which is either a string like `https://example.com` or an object with mandatory properties `{ hostName: string; protocol: string }`.
closes #54
=> fix: deprecate host and protocol in `buildItemLinkForBuilder`

src/interfaces/extra.ts, src/services/app/index.ts, src/services/app/interfaces/extra.ts, src/services/file/interfaces/extra.ts, src/utils/extra.ts, src/utils/index.ts
This PR apps types referenced by `builder` in https://github.com/graasp/graasp-builder/issues/500 and `ui` in https://github.com/graasp/graasp-ui/pull/199.
This PR needs #60 to be closed in order for the builder to work.
closes #62
=> 62 upstream types

src/constants/index.ts, src/constants/mimeTypes.ts
This PR adds MimeTypes constants in sdk. The mimetypes in ui are going to be deprecated to enforce usage of these ones.
Comments on the naming convention to use are welcome.
closes #89
=> feat: add mimetypes

src/services/items/interfaces/item.ts, src/services/members/interfaces/member.ts
This PR adds the enableSaveActions property in Member interface and ItemSettings interface, which will be used on GDPR.
=> feat: add enableSaveActions property

src/frontend/index.ts, src/frontend/ui.ts
This PR exports the `ThumbnailSize` constant enum to be used in `@graasp/ui`, `@graasp/query-client`, `@graasp/builder` and `@graasp/player`.
closes #99
=> feat: add ThumbnailSize to exported constants

src/constants/constants.ts, src/services/items/interfaces/item.ts
This PR adds the embedded link item settings types to the discriminated item so we can have correct and accurate typing when accessing the EmbeddedLinkItem type. `showLinkButton` is now correctly typed as `boolean | undefined` when access inside a type guard on the item `type` property.
=> fix: add embedded link item settings

src/utils/cookie.ts
This PR improves the type of the `saveUrlForRedirection` util function to allow the omission of the domain parameter. This parameter can be `undefined` and will then default to the current domain.
=> fix: allow optional domain on saveUrlForRedirection

src/services/items/interfaces/item.ts
This PR updates the type of `Item` to reflect the nullable property of `description`.
This is correct with the item schema defined in the backend.
=> fix(type): item.description to be nullable

src/frontend/index.ts, src/frontend/ws-client.ts
Closes #268 
Note: the WS client was copy pasted from query-client, however the restart mechanism bit was added:
https://github.com/graasp/graasp-sdk/blob/2a433d63ef9459470cc5a5cf44bb91bf4733a811/src/frontend/ws-client.ts#L95-L133
=> feat: move websocket client to sdk, always restart ws client

src/types.ts
This PR adds a utility type `Optional<T, K>` that combines `Omit` and `Pick` to make some properties of the input type optional.
We use this in a lot of our inputs in query-client and so on to allow some keys to be undefined and then throw an error of they are.
This utility will help to abstract that base type away and provide a nice type to work with
=> feat(types): add `Optional<T, K>` utility type to make some properties of a type optional

src/interfaces/extra.ts, src/services/app/interfaces/extra.ts, src/services/etherpad/interfaces/etherpad.ts, src/services/file/interfaces/extra.ts, src/services/h5p/interfaces/extra.ts, tsconfig.json
In this PR I remove the `UnknownExtra` to enforce stronger types and remove errors with types generalizing to `[x: string]: unknown` in TS.
=> fix: remove `UnknownExtra`

src/constants/itemType.ts, src/services/action/interfaces.ts, src/services/app/interfaces/appAction.ts, src/services/app/interfaces/appData.ts, src/services/app/interfaces/appSetting.ts, src/services/categories/types.ts, src/services/chat/types.ts, src/services/flag/types.ts, src/services/invitation/types.ts, src/services/item-like/types.ts, src/services/item-login/types.ts, src/services/item-memberships/interfaces/item-membership.ts, src/services/item-published/types.ts, src/services/item-recycled/types.ts, src/services/item-tags/types.ts, src/services/item-validation/types.ts, src/services/items/interfaces/item.ts, src/services/members/interfaces/member.ts, src/utils/extra.ts
This PR updates the types to use `DiscriminatedItem` instead of `Item`.
This way the Record type of the key `item` will match `ItemRecord` since `ItemRecord` derives from `DiscriminatedItem` and not  `Item`.
close #270
=> fix: use `DiscriminatedItem` instead of `Item`

package.json, src/utils/navigation.ts, yarn.lock
> **Note** 
It was safe to remove the resolutions as we are now depending on higher versions of those packages:
<details>
<summary>Full dependencies for <em>minimist</em></summary>
<pre>
❯ yarn why minimist 
└─ @commitlint/read@npm:18.1.0
└─ minimist@npm:1.2.8 (via npm:^1.2.6)
</pre>
</details>
<details>
<summary>Full dependencies for <em>@babel/core</em></summary>
<pre>
❯ yarn why @babel/core
├─ @jest/transform@npm:29.7.0
│  └─ @babel/core@npm:7.23.2 (via npm:^7.11.6)
│
├─ istanbul-lib-instrument@npm:5.1.0
│  └─ @babel/core@npm:7.23.2 (via npm:^7.12.3)
│
├─ istanbul-lib-instrument@npm:6.0.0
│  └─ @babel/core@npm:7.23.2 (via npm:^7.12.3)
│
├─ jest-config@npm:29.7.0
│  └─ @babel/core@npm:7.23.2 (via npm:^7.11.6)
│
├─ jest-config@npm:29.7.0 [3a6a7]
│  └─ @babel/core@npm:7.23.2 (via …
=> fix: remove qs dep

src/constants/host.ts, src/index.ts, src/interfaces/shortLink.ts
The ClientHostManager was instanced  in the SDK to set default Hosts and Prefix. 
The problem is its add a side effect. Indeed, each time the SDK is imported, a ClientHostManager a new instance is created.
To avoid this unexpected side effect, the instantiation is removed from the SDK and must be done in the backend for example.
=> fix: remove ClientHostManager instantiation in the SDK

src/interfaces/shortLink.ts
This PR update the payload of short links to allow to send directly the item id like: `{..., itemId: "..." } instead of {..., item: { id: ... } }`. 
This updates simplify the usage of the API and increase clarity because it's avoid to send incomplete item.
The transformation from itemId to item is done in the backend directly.
=> Update the short link's payload from item to itemId

package.json, src/utils/cookie.test.ts, src/utils/navigation.test.ts, test/fixtures.ts, tsconfig.build.json, tsconfig.json, tsconfig.node.json, vite.config.ts, yarn.lock
In this PR I:
- setup the build process to use vite library mode
This has multiple advantages:
- it creates 2 bundles: 
- 1 ESM
- 1 CommonJS
- but the package can be an ESM package
- it allows us to decide which dependencies we want to bundle and which ones we want to externalise (added in the rollupOptions) so the consumer can provide theirs.
- we already use vitest for tests (mhmmm so fast) so why bother with a different build pipeline
This change involved changing a bit the tsconfigs etc. 
Please ask any questions where you have doubts or are curious of some settings.
=> fix: build with vite

src/services/item-geolocation/types.ts
I still keep the country besides so it's easier to query per country.
I could have plenty of rows for the address (eg. road, state, country_code, postal_code, etc) but they just look infinite so I just the default label string I was provided. I think it's still okay to keep it simple as we're not planning (yet) complex geolocation search.
=> feat: add address in geolocation

package.json, src/factories.ts, src/services/items/index.ts, src/services/items/itemFactory.test.ts, src/services/members/index.ts, tsconfig.json, vite.config.ts
In this PR:
- in order to reduce bundle size when used by consumers, the factories have been moved to a separate entry-point `@graasp/sdk/factories`
- using this import only in test files should reduce the bundle size of the client apps while allowing to keep the factories in this repo.
=> fix(build): split bundle into production and test code

src/navigation/navigation.test.ts, src/navigation/navigation.ts
In this PR:
- add redirection Url option in sign in path. This allows to redirect users to where they were when they need to sign in again.
- fix #449
=> fix: add redirection Url in sign in path

src/constants/limits.ts
In this PR I add the username constants for validation. They are used in Auth and Account.
The values are taken from the backend:
- in the schema for the MIN: 1
- in the entity for the MAX: 100
fix #478
=> fix: add username constants

src/item/itemSettings.ts, src/typeUtils.ts
- Allows item's license setting to be null.
- Sending null to the backend will remove the setting.
=> feat: set item's license setting nullable

src/constants/limits.ts
Should we also increase the delete limit to allow deleting content that was copied ?
fix #535
=> fix: increase copy limit to 400

src/itemPublished/itemPublished.ts
Because now the frontend unpublish before setting published items to private, this status is not needed anymore (because it is unreachable)
=> feat: remove status NotPublic from PublicationStatus

src/item/appItem/appItem.factory.test.ts, src/item/appItem/appItem.factory.ts, src/item/appItem/appItem.ts
In this PR I removed the unused `item.extra.app.settings` property.
This property was unused and we did not need it. It was typed as `unknown` which made some castings necessary in the backend. 
If we want to keep it, we should instead opt for a generic type that extends the empty object.
=> fix: remove extra.app.settings key in item

src/mimeTypes/mimeTypes.ts
In this PR I add support for the audio files that use the `.m4a` file extension, that are detected as `audio/x-m4a`.
=> feat: add support for AAC, FLAC, OGG and m4a

src/item/itemUtils.test.ts, src/item/itemUtils.ts
The median time on `1'000` execution on my machine for a random path of `10'000` ids went from 5ms to 2ms.
I know it's not a big improvement, but I feel like I'm using this function a lot and it could be easily faster.
=> feat: improve getChildFromPath time complexity

src/app/app.ts
To avoid apps to break (we don't have control on some of them) we will set back the `member` key so they can continue to work.
=> feat: add legacy member key in app types

src/enums/thumbnailSizes.ts, src/index.ts, src/item/packedItem.ts
I decided to move back the `ThumbnailSizeInPackedItem` in the `thumbnailSizes.ts` to avoid transpiling weird type in commonJS (no issue with ESM).
=> fix(type): move ThumbnailSizeInPackedItem in thumbnailSizes to avoid any

src/index.ts, src/member/constants.test.ts, src/member/constants.ts
Add this username regex to SDK to unify the behaviour across the components. Relates to https://github.com/graasp/graasp/issues/1311
=> feat: add a global username regex

package.json, src/member/password.ts, src/validation/isPasswordStrong.test.ts, src/validation/isPasswordStrong.ts, src/validation/utils.test.ts, src/validation/utils.ts, yarn.lock
In this PR I propose to remove the dependency `validator` since we only use the password checking and email checking functions. It would be easy for us to include the code of these functions in our own codebase and remove the dependency on that package. This will also allow us to properly test these functions with the inputs that seem relevant to us.
Why we should try to remove our dependency on this module is best illustrated by an image:
We see that in the production bundle of account, this package takes around 250Kb (rendered) of space. As we only use `isStrongPassword` and `isEmail` this seems a bit much.
=> feat: make own validation for password

src/member/member.ts
Remove property from member profile that is not returned by the backend anymore.
=> fix: remove member property from member profile

src/member/password.ts, src/validation/isPasswordStrong.ts
In this PR I fix a type issue with the recently refactored `isStrongPassword` function. 
This function as ported from the `validator.js` package was accepting an `options` parameter that could contain the `returnScore` option. If this was present it would return the score of the password. So the signature of the function was `number | boolean`. I think this does not makes sens with the name of the function `is*` where we expect it to return `boolean` exclusively. So I split the functionality in two functions: `isStrongPassword` and `getPasswordScore` that have their own purpose.
=> fix: strong password type

.husky/commit-msg, .husky/post-commit, .husky/pre-commit, .husky/pre-push, src/item/baseItem.ts, src/item/factory.test.ts, src/item/factory.ts
- **fix: remove displayName**
- **chore: remove husky shebang**
=> fix: remove displayName

src/constants/paths.ts, src/hostManager/clientManager.test.ts, src/hostManager/clientManager.ts, src/index.ts, src/navigation/navigation.test.ts, src/navigation/navigation.ts
The client manager creates necessary links, mostly used for redirection in the backend or frontend.
The client manager can also generate general links, not only item links. This allows us to remove utility functions such as `builderBuilderLinkForItem` (or something similar)
=> feat: update client manager
