graasp/graasp-sdk

src/constants/contexts.ts

refactor: lowercase context names

---

src/utils/array.test.ts
src/utils/array.ts
src/utils/error.test.ts
src/utils/error.ts
src/utils/index.ts
src/utils/member.test.ts
src/utils/member.ts

feat: add partition util, refine pseudonymized member util

---

src/constants/itemType.ts

feat: add h5p item type

---

src/utils/cookie.test.ts
src/utils/cookie.ts
test/fixtures.ts

feat: add lang cookie utils

---

package.json
src/utils/immutable.test.ts
src/utils/immutable.ts
src/utils/index.ts
yarn.lock

feat: add convertJS function

---

src/constants/mentions.ts

This PR adds the enum for the email frequency preference of the user.
closes #44

feat: add emailFreq enum

---

.github/workflows/release-please.yml

This PR adds release please to version this package.
closes #56

chore(ci): add release-please

---

.github/workflows/release-please.yml
package.json

This PR updates release-please with composite workflow for npm publish.
closes #64

chore: update release-please with npm publish

---

package.json
src/utils/navigation.test.ts
src/utils/navigation.ts

60 pdf link

---

src/constants/itemType.ts
src/services/etherpad/index.ts
src/services/etherpad/interfaces/etherpad.ts
src/services/index.ts
src/utils/navigation.ts

Closes #53 
- Adds etherpad item type
- Adds etherpad plugin return interface

feat: add etherpad types

---

src/services/file/interfaces/extra.ts

feat: add file size property

---

src/constants/limits.ts

refactor: increase limits to 130

---

src/interfaces/extra.ts
src/services/h5p/interfaces/extra.ts
src/services/h5p/interfaces/task-manager.ts
src/services/items/interfaces/item.ts
src/utils/extra.ts

feat: add document flavor extra property

---

src/utils/extra.ts

This PR adds building methods to create item extras.
Will be useful to remove some duplicated utils from builder and player.
closes #92

feat: add building utilities for extra

---

src/services/items/interfaces/item.ts

fix: etherpad extra type

---

package.json
src/declarations.ts
src/services/etherpad/index.ts
src/services/etherpad/interfaces/service.ts
yarn.lock

Closes #142
**TODO**: bump @graasp/etherpad-api with fixes to query API

feat: add etherpad service

---

src/services/items/interfaces/item.ts

This PR adds th `lang` prop in the ItemSettings type.

fix: add lang prop in ItemSettings

---

src/services/items/interfaces/item.ts
src/services/members/interfaces/member.ts

This PR adds the prop `emailFreq` to the `MemberExtra` type.

fix: add emailFreq

---

package.json
src/services/file/interfaces/configuration.ts
src/utils/item.test.ts
yarn.lock

This PR changes the aws package to use the latest one.
I've also fixed dependabot alerts.

refactor: update dependencies

---

src/frontend/types.ts
src/services/index.ts
src/services/item-favorite/index.ts
src/services/item-favorite/types.ts

Based on branch typeorm
Related PRs:
* core: https://github.com/graasp/graasp/pull/379
* query-client: https://github.com/graasp/graasp-query-client/pull/275
* Builder: https://github.com/graasp/graasp-builder/pull/656

feat: add favorite type

---

src/frontend/types.ts
src/services/file/interfaces/extra.ts
src/services/index.ts

feat: adds settings and altText to fileItems

---

src/services/members/interfaces/member.ts

feat: adds completed tour extra to member

---

.eslintrc
src/services/action/aggregation.ts
src/services/action/index.ts

221 agg enums

---

.all-contributorsrc
README.md

docs: add readme

---

package.json
src/utils/date.test.ts
src/utils/date.ts
yarn.lock

I've factored out `formatDate` from Builder to reuse it Account.

feat: add format date util

---

src/constants/index.ts
src/constants/triggers.ts
src/services/item-published/types.ts

fix: item published type

---

src/constants/context.ts

fix: add account context

---

src/constants/mimeTypes.ts

Ref https://github.com/graasp/graasp-ui/issues/590

fix: add support for webp image format

---

.github/workflows/test.yml
src/utils/item.test.ts
src/utils/item.ts
tsconfig.json
yarn.lock

feat: add sortChildrenWith

---

src/services/items/interfaces/item.ts
src/services/items/interfaces/itemSettings.ts

Should it be `lang` or `language`?

feat: add item language

---

src/config.ts

fix: remove DEFAULT_LANG

---

src/interfaces/extra.ts

This PR adds the `None` flavor so we can enjoy life in its simplest form.
Should it have been called `vegan` 🌱  ?

fix: add none flavor

---

.gitignore
README.md
package.json
src/cookie/cookie.ts
src/websockets/index.ts
tsconfig.cjs.json
tsconfig.esm.json
tsconfig.types.json

In this PR:
- expose a ESM package
- expose a CJS package
- fix the fields in package.json
- add documentation in readme
This PR has been tested with the Backend in https://github.com/graasp/graasp/pull/838
This PR has been tests in Builder https://github.com/graasp/graasp-builder/pull/1032
THIS PR is used in Query-client https://github.com/graasp/graasp-query-client/pull/647

fix(build): exports issues

---

src/enums/descriptionPlacement.ts
src/index.ts
src/item/itemSettings.ts

This PR refer to graasp/graasp-ui#694.

feat: add descriptionPlacement in itemSettings

---

src/chatbot/chatbot.ts
src/index.ts

fix: add gpt version enum

---

src/enums/triggers.ts

feat: add member login action trigger

---

src/action/action.ts

feat: create export action formatting

---

.gitignore
src/item/itemUtils.test.ts
src/item/itemUtils.ts

fix: allow path to be undefined in getIdsFromPath util

---

src/itemPublished/itemPublished.test.ts
src/itemPublished/itemPublished.ts

feat: define allowed types to be published

---

src/enums/alignment.ts
src/index.ts
src/item/baseItem.ts
src/item/fileItem/fileItem.ts
src/item/itemSettings.ts

In this PR I:
- added the `alignment` key in the file settings
- added the `Alignment` enum and related functions

feat: add alignment enum

---

src/enums/alignment.ts

Refactor function and move it to UI

fix: remove ui-related functions

---

src/member/member.ts

feat: add new member storage items type

---

src/index.ts
src/member/member.ts
src/pagination/pagination.ts

In this PR I add pagination types following the discussion we had.

fix: add pagination types

---

src/mimeTypes/mimeTypes.test.ts
src/mimeTypes/mimeTypes.ts

feat: add docs mime types

---

src/index.ts
src/membershipRequest/membershipRequest.ts

fix https://github.com/graasp/graasp/issues/1220

feat(membership request): data transfert objects

---

src/constants/limits.ts

Update the ZIP file max size to reflect the backend's limit.

feat: update the new ZIP max size

---

src/constants/limits.ts
src/member/member.test.ts
src/member/member.ts

ref https://github.com/graasp/graasp-builder/issues/1505

fix: add member utils

---

src/navigation/navigation.test.ts
src/navigation/navigation.ts

In this PR I add the option to specify the language when building the signin url.

fix: add lang in signin url

---

src/member/member.test.ts
src/member/member.ts

Fixes https://github.com/graasp/graasp-account/pull/375#discussion_r1820293494

fix: make lang return undefined when the account is not defined

---

src/enums/context.ts
src/hostManager/clientManager.test.ts
src/hostManager/clientManager.ts

Adds `home` Context so we can easily build url to redirect to home.

feat: add home context

---

src/item/events/itemFeedbackOperationEvent.ts

ref https://github.com/graasp/graasp/pull/1839

feat: change recycle feedback type

---

src/item/fileItem/fileItem.factory.test.ts
src/item/fileItem/fileItem.factory.ts
src/item/fileItem/fileItem.ts
src/item/item.test.ts
src/item/item.ts
src/item/itemType.ts

feat: remove s3 item type

---

src/search/search.ts
src/tag/factory.ts
src/tag/tag.ts

In this PR I update `TagCategory` from enum to const object.
Associated PR in Client: https://github.com/graasp/client/pull/993

fix: update TagCategory to use const

---

src/chatbot/chatbot.ts

Added GPT5(-mini/nano) constants to enable apps to call these models.

feat: add GPT5 generation models
